apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: '2024-03-22T06:07:13Z'
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-juice-shop
  name: juice-shop
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-juice-shop
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-juice-shop
      namespace: default
    spec:
      affinity: {}
      containers:
        - image: bkimminich/juice-shop
          imagePullPolicy: Always
          name: container-0
          ports:
            - containerPort: 3000
              name: juice-shop
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["default/juice-shop"]'
  name: juice-shop-loadbalancer
  namespace: default
spec:
  loadBalancerClass: loxilb.io/loxilb
  allocateLoadBalancerNodePorts: true
  ports:
    - name: juice-shop
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-juice-shop
  type: ClusterIP
